# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: dockerRegistryServiceConnection
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        dockerFile: '$(Build.SourcesDirectory)/app/Dockerfile'
        repository:  Flowable
        tags: V1
    - task: AzurePowerShell@5
      displayName: Check image has published
      inputs:
        azureSubscription: 'Visual Studio Enterprise (9e4ebf69-d70b-48bd-bb7e-0545daea4a64)'
        inline: 'az acr run --registry davejContainerRegistry45 --cmd ''$Registry/flowable:V1'' /dev/null'